version: 2.1

workflows:
  test_deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.8.9
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: pip install pytest
      - run: 
          name: Run Tests
          command: pytest
